import React, { useEffect, useState } from "react";
import { View } from "react-native";
import { GestureHandlerRootView, ScrollView } from "react-native-gesture-handler";
import { coreStyles } from "../styles/styles";
import Trail from "./subPages/Trail";
import Filters from "./subPages/Filters";
import { filterJson } from "../store";
import { StyleSheet } from "react-native";
import Search from "./subPages/Search";

const trails = require("../json/trail_data.json"); //dummy data generated by chatGPT

/**Applies filters in filters object and returns array*/


export const TrailList = ({ trail }) => {
  return (
    <ScrollView style={allTrailsStyles.trailList}>
      {trail.map((trail, index) => ( //chatGPT was asked 'How to implament a foor loop into jsx?'
        <Trail key={index} trail={trail} />
      ))}
    </ScrollView>
  )
}

export const filterApply = () => {
  console.log("filters in effect >> easy:" + filterJson.easy + " medium:" + filterJson.medium + " hard:" + filterJson.hard);
  let trailArray = [];

  let easyArray = [];
  let medArray = [];
  let hardArray = [];

  for (let i = 0; i < trails.length; i++) {
    const item = trails[i];

    if (item.distanceFromUser <= filterJson.maxDistanceFromUser) {
      if (item.difficulty === 'E') {
        easyArray.push(item);
      } else if (item.difficulty === 'M') {
        medArray.push(item);
      } else if (item.difficulty === 'H') {
        hardArray.push(item);
      }
    }
  }

  if (filterJson.easy) {
    easyArray.forEach((item) => {
      trailArray.push(item);
    });
  }
  if (filterJson.medium) {
    medArray.forEach((item) => {
      trailArray.push(item);
    });
  }
  if (filterJson.hard) {
    hardArray.forEach((item) => {
      trailArray.push(item);
    });
  }

  return trailArray;
};

export default function AllTrails() {
  const [trailsState, setTrails] = useState([]);

  const updateTrails = () => {
    const filteredTrails = filterApply();
    setTrails(filteredTrails);
  };

  useEffect(() => {
    updateTrails();
  }, []);
  filterApply();

  return (
    <GestureHandlerRootView style={coreStyles.gestureHandlerRootView}>
      <TrailList trail={trailsState} />
      <View style={allTrailsStyles.bottomRow}>
        <Filters />
        <Search />
      </View>
    </GestureHandlerRootView>
  );
};


const allTrailsStyles = StyleSheet.create({
  homeTop: {
    flex: 0.09,
    margin: 10,
  },

  trailList: {
    flex: 0.91,
    borderRadius: 10,
  },
  bottomRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 10,
  },
});