import React, { useEffect, useState } from "react";
import { View } from "react-native";
import { GestureHandlerRootView, ScrollView } from "react-native-gesture-handler";
import Trail from "./subPages/Trail";
import Filters from "./subPages/Filters";
import { StyleSheet } from "react-native";
import Search from "./subPages/Search";

const trailList = require("../json/trail_data.json"); //dummy data generated by chatGPT


/**Component containing the All Trails page for the user to view all the aviable trails and filter them using the filter modal called
 * @returns {GestureHandlerRootView}
*/
export default function AllTrails() {
  const [filters, setFilters] = useState({
    maxDistanceFromUser: 10,
    maxDistance: 10,
    hard: true,
    medium: true,
    easy: true,
  });

  const [filteredList, setFilteredList] = useState([]);

  const updateFilters = (newFilters) => {
    setFilters(newFilters);
    applyFilters();
  };

  /**Uses filters to create new list of accepted trails*/
  const applyFilters = () => {
    const newFilteredList = [];
    for (let i = 0; i < trailList.length; i++) {
      if (
        trailList[i].distanceFromUser <= filters.maxDistanceFromUser &&
        trailList[i].distance <= filters.maxDistance
      ) {
        if (filters.easy && trailList[i].difficulty === 'E') {
          newFilteredList.push(trailList[i]);
        }
        if (filters.medium && trailList[i].difficulty === 'M') {
          newFilteredList.push(trailList[i]);
        }
        if (filters.hard && trailList[i].difficulty === 'H') {
          newFilteredList.push(trailList[i]);
        }
      }
    }
    setFilteredList(newFilteredList);
  };

  useEffect(() => {
    applyFilters();
  }, [filters]);

  return (
    <GestureHandlerRootView style={{flex: 1}}>
      <ScrollView >
        {filteredList.map((trail, index) => (
          <Trail key={index} trail={trail} />
        ))}
      </ScrollView>
      <View style={allTrailsStyles.bottomRow}>
        <Filters update={updateFilters} />
        <Search />
      </View>
    </GestureHandlerRootView>
  );
};

const allTrailsStyles = StyleSheet.create({
  bottomRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 10,
  },
});