import React from "react";
import { Text, View, Pressable } from "react-native";
import { GestureHandlerRootView, ScrollView } from "react-native-gesture-handler";
import { coreStyles } from "../styles/styles";
import Trail from "./subPages/Trail";
import MaxDistance from "./subPages/MaxDistance";

const cardData = require("../json/trail_data.json"); //dummy data generated by chatGPT


export default function Home() {
  return (
    <GestureHandlerRootView style={coreStyles.gestureHandlerRootView}>

      <View style={coreStyles.homeTop}>
        <Text style={coreStyles.h1}>Trails Near You</Text>
        <View style={{ padding: 10 }} />
        <MaxDistance />
      </View>

      <ScrollView style={coreStyles.scrollView}>
        {cardData.trails.map((trail, index) => ( //chatGPT was asked 'How to implament a foor loop into jsx?'
          <Trail key={index} trail={trail} />
        ))}
      </ScrollView>
    </GestureHandlerRootView>
  );
}
