import React, { useState } from "react";
import { Text, View, StyleSheet, Dimensions, SafeAreaView, Button, Pressable } from "react-native";
import { GestureHandlerRootView, ScrollView } from "react-native-gesture-handler";
import { coreStyles } from "../styles/styles";
import Trail from "./Trail";

const cardData = require("../json/trail_data.json"); //dummy data generated by chatGPT

const Card = ({ content }) => {
  return (
    <View>
      <View style={coreStyles.card}>
        <Text style={coreStyles.cardHeader}>{content.name}</Text>

        <View style={coreStyles.cardStats}>
          <Text><Text style={{ fontWeight: 'bold' }}>Distance: </Text>{content.distance} |</Text>
          <Text> <Text style={{ fontWeight: 'bold' }}>Difficulty:</Text> {content.difficulty} |</Text>
          <Text> <Text style={{ fontWeight: 'bold' }}>Distance From You: </Text></Text>
        </View>

        <Text style={coreStyles.cardDesc}>{content.description}</Text>
      </View>

      <View style={{ padding: 10 }} />
    </View>
  );
}



export default function Home() {
  return (
    <GestureHandlerRootView style={coreStyles.gestureHandlerRootView}>

      <View style={coreStyles.homeTop}>
        <Text style={coreStyles.h1}>Trails Near You</Text>
        <View style={{ padding: 10 }} />
        <Pressable style={coreStyles.distButton}>
          <Text style={{ fontWeight: 'bold', fontSize: 20 }}>Max Distance</Text>
        </Pressable>
      </View>

      <ScrollView style={coreStyles.scrollView}>
        {cardData.trails.map((trail, index) => ( //chatGPT was asked 'How to implament a foor loop into jsx?'
          <Card key={index} content={trail} />
        ))}
        <Trail/>
      </ScrollView>
    </GestureHandlerRootView>
  );
}
