import React from "react";
import { Text, View, Pressable } from "react-native";
import { GestureHandlerRootView, ScrollView } from "react-native-gesture-handler";
import { coreStyles } from "../styles/styles";
import Trail from "./subPages/Trail";
import Filters from "./subPages/Filters";
import { filterJson } from "../store";

const cardData = require("../json/trail_data.json"); //dummy data generated by chatGPT


/**Applies filters in filters object and returns array*/
const filterApply = () => {
  let trailArray = [];
  let easyArray = [];
  let medArray = [];
  let hardArray = [];

  for (let i = 0; i < cardData.length; i++) {
    const item = cardData[i];


    if (item.distanceFromUser <= filterJson.maxDistanceFromUser) {
      if (item.difficulty == 'E') {
        easyArray.push(item);
      } else if (item.difficulty == 'M') {
        medArray.push(item);
      } else if (item.difficulty == 'H') {
        hardArray.push(item);
      }
    }
  }

  if (filterJson.easy) {
    easyArray.forEach((item) => {
      trailArray.push(item);
    });
  }
  if (filterJson.medium) {
    medArray.forEach((item) => {
      trailArray.push(item);
    });
  }
  if (filterJson.hard) {
    hardArray.forEach((item) => {
      trailArray.push(item);
    });
  }
  return trailArray;
}

export const TrailList = ({ trails }) => {
  return (
    <ScrollView style={coreStyles.scrollView}>
      {trails.map((trail, index) => ( //chatGPT was asked 'How to implament a foor loop into jsx?'
        <Trail key={index} trail={trail} />
      ))}
    </ScrollView>
  )
}

export default function NearYou() {
  return (
    <GestureHandlerRootView style={coreStyles.gestureHandlerRootView}>

      <View style={coreStyles.homeTop}>
        <Text style={coreStyles.h1}>Trails Near You</Text>
        <Filters />
      </View>
      <TrailList trails={filterApply()} />


    </GestureHandlerRootView>
  );
}
